version: '3.9'
services:
  frontend:
    build: ./frontend
    container_name: react_frontend
    expose:
      - "80"                 # expone solo internamente al network
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.react_frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.react_frontend.rule=Host(`TU_SUBDOMINIO`)"
      - "traefik.docker.network=traefik-net"

  backend:
    build: ./backend
    container_name: flask_backend
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - OAUTHLIB_INSECURE_TRANSPORT=1
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.flask_backend.loadbalancer.server.port=5000"
      - "traefik.http.routers.flask_backend.rule=Host(`api.TU_SUBDOMINIO`)"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external: true
